spring:
  datasource:
    url: jdbc:postgresql://dpg-d77l14chg0os73ccsl0g-a.oregon-postgres.render.com:5432/memo_db_cyn8
    username: memo_db_cyn8_user
    password: DSPFrrmX5lyYuQfMRgs2LHtHNmF57Mm2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true